name: Main
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  everything:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Lint Format
        run: pnpm lint:format
      - name: Type Check
        run: pnpm type-check
      - name: Test
        run: pnpm test
      - name: Build
        run: pnpm build
